### ISSUE TITLE
Add support for full conda environment detection when type `pdm init`

### ISSUE THREAD

**Issue by gvariable** [macro128/pdm-conda#13]
I recently raised an issue on the `pdm` project regarding `conda`. However, a contributor kindly suggested that it would be more appropriate to post the issue here, providing a link to the relevant GitHub issue: [link](https://github.com/pdm-project/pdm/issues/2144).

**Comment by macro128** [comment]
Hi! I was planning on adding `mamba/micromamba` environment management to the plugin, I think I can add it with the functionality you proprose

**Comment by macro128** [comment]
Hi! `pdm init` now works using Conda runner since `v0.12.0`
